//! Row id codec — Crockford base32 over 16 random bytes.
//!
//! Per [ADR 0004][adr0004] we deliberately do NOT use ULIDs /
//! `UUIDv7` — their embedded timestamps would leak into the
//! plaintext primary key column and defeat the day-quantisation
//! on `updated_day`.
//!
//! The encode / decode must be byte-identical to the JS side
//! (`packages/storage/src/id.ts`) so the AAD bytes
//! [`crate::codec::aad_for`] produces match what the page-side
//! encryption uses. A drift in any direction breaks tag verification
//! on cross-side reads.
//!
//! [adr0004]: https://github.com/stephane-segning/opfs-webauthn/blob/main/docs/adrs/0004-sqlite-opfs-storage.md

use alloc::string::String;
use alloc::vec::Vec;

use crate::error::Error;

/// Crockford base32 alphabet. Avoids `I`, `L`, `O`, `U` to keep the
/// human-spoken codes unambiguous. Lowercase variants decode the same
/// (see [`decode`]).
const CROCKFORD: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// Length in bytes of a row id at rest in the BLOB primary key.
pub const ROW_ID_BYTES: usize = 16;

/// Length in characters of a row id once Crockford-encoded.
/// `ceil(128 / 5) = 26`.
pub const ROW_ID_CHARS: usize = 26;

/// Encode 16 bytes as 26 Crockford-base32 characters.
///
/// Errors with [`Error::WrongRowIdLength`] when the input isn't
/// exactly [`ROW_ID_BYTES`]. Returns an uppercase ASCII string; the
/// JS-side encoder also emits uppercase so the AAD matches.
pub fn encode(bytes: &[u8]) -> Result<String, Error> {
    if bytes.len() != ROW_ID_BYTES {
        return Err(Error::WrongRowIdLength {
            expected: ROW_ID_BYTES,
            got: bytes.len(),
        });
    }
    let mut out = String::with_capacity(ROW_ID_CHARS);
    let mut bits = 0u32;
    let mut value = 0u32;
    for &byte in bytes {
        value = (value << 8) | u32::from(byte);
        bits += 8;
        while bits >= 5 {
            bits -= 5;
            let idx = ((value >> bits) & 0b1_1111) as usize;
            out.push(CROCKFORD[idx] as char);
        }
    }
    if bits > 0 {
        // Left-shift the remaining `bits` into the top of a 5-bit
        // group; the unused low bits are zero. JS does the same.
        let idx = ((value << (5 - bits)) & 0b1_1111) as usize;
        out.push(CROCKFORD[idx] as char);
    }
    Ok(out)
}

/// Decode a 26-char Crockford-base32 id back into 16 bytes.
///
/// Accepts lowercase letters by uppercasing each char before lookup,
/// matching the JS side. Returns [`Error::WrongRowIdLength`] if the
/// id isn't exactly [`ROW_ID_CHARS`] chars, and
/// [`Error::InvalidRowIdChar`] on any character outside the Crockford
/// alphabet (post-uppercase).
pub fn decode(id: &str) -> Result<Vec<u8>, Error> {
    if id.chars().count() != ROW_ID_CHARS {
        return Err(Error::WrongRowIdLength {
            expected: ROW_ID_CHARS,
            got: id.chars().count(),
        });
    }
    let mut out = Vec::with_capacity(ROW_ID_BYTES);
    let mut bits = 0u32;
    let mut value = 0u32;
    for ch in id.chars() {
        let upper = ch.to_ascii_uppercase();
        let idx = CROCKFORD
            .iter()
            .position(|&c| c == upper as u8)
            .ok_or(Error::InvalidRowIdChar { ch })?;
        // `position` returns 0..32 (alphabet length); fits trivially
        // in u32 without truncation. Cast is exhaustively
        // bounds-checked by the previous statement.
        #[allow(clippy::cast_possible_truncation, reason = "idx < 32")]
        let idx_u32 = idx as u32;
        value = (value << 5) | idx_u32;
        bits += 5;
        if bits >= 8 {
            bits -= 8;
            #[allow(
                clippy::cast_possible_truncation,
                reason = "value >> bits keeps the relevant byte in the low 8 bits by construction"
            )]
            out.push(((value >> bits) & 0xff) as u8);
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Frozen JS-side round-trip vectors. Generated by running the JS
    // encoder (`packages/storage/src/id.ts`) over these exact byte
    // arrays. If these tests break, either the Rust codec drifted
    // from the JS one or both need to land a JS-side update too.
    //
    // Reproduce with `node` once:
    //   node -e "
    //     const A='0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    //     function enc(bytes){let b=0,v=0,o='';for(const x of bytes){
    //       v=(v<<8)|x;b+=8;while(b>=5){b-=5;o+=A[(v>>>b)&31]}}
    //       if(b)o+=A[(v<<(5-b))&31];return o}
    //     console.log(enc(new Uint8Array(16)));
    //   "
    const VECTORS: &[(&[u8; 16], &str)] = &[
        (&[0; 16], "00000000000000000000000000"),
        (&[0xff; 16], "ZZZZZZZZZZZZZZZZZZZZZZZZZW"),
        (
            // 0x00112233_44556677_8899aabb_ccddeeff
            &[
                0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
                0xee, 0xff,
            ],
            "008J4CT4ANK7F24SNAXWSQFEZW",
        ),
    ];

    #[test]
    fn encode_matches_js_vectors() {
        for (bytes, expected) in VECTORS {
            assert_eq!(encode(*bytes).unwrap(), *expected, "input {bytes:02x?}");
        }
    }

    #[test]
    fn decode_round_trips() {
        for (bytes, expected) in VECTORS {
            assert_eq!(decode(expected).unwrap(), *bytes, "input {expected}");
        }
    }

    #[test]
    fn encode_wrong_length_errors() {
        assert!(matches!(
            encode(&[0; 15]),
            Err(Error::WrongRowIdLength { expected: 16, got: 15 })
        ));
        assert!(matches!(
            encode(&[0; 17]),
            Err(Error::WrongRowIdLength { expected: 16, got: 17 })
        ));
    }

    #[test]
    fn decode_lowercase_works() {
        let upper = encode(&[0x88; 16]).unwrap();
        let lower = upper.to_ascii_lowercase();
        assert_eq!(decode(&lower).unwrap(), decode(&upper).unwrap());
    }

    #[test]
    fn decode_invalid_char_errors() {
        // The encoded length must still match ROW_ID_CHARS (26) so we
        // reach the per-char check. Insert an `I` (illegal in
        // Crockford) at a fixed position.
        let mut bad = String::from("00000000000000000000000000");
        bad.replace_range(5..6, "I");
        assert!(matches!(decode(&bad), Err(Error::InvalidRowIdChar { .. })));
    }
}
